# Generated by Django 4.2.3 on 2023-08-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellido', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('bultos', models.ManyToManyField(to='aplicacion.bulto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Entregado', 'Entregado')], max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.envio')),
            ],
        ),
    ]
